quarkus.application.name=syirkah-asset-service
quarkus.http.port=8084
quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=postgresql://localhost:5432/syirkah_asset
quarkus.hibernate-orm.database.generation=none
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
