package tech.kayys.erp.crm.application.api.command;

import tech.kayys.erp.foundation.application.Command;
import tech.kayys.erp.crm.domain.identifier.ReportId;

import java.time.Instant;

/**
 * Command to generate a conversion report.
 */
public record GenerateConversionReportCommand(
        ReportId reportId,
        String period,
        Instant periodStart,
        Instant periodEnd,
        String generatedBy
) implements Command<ReportId> {

    public GenerateConversionReportCommand {
        if (period == null || period.trim().isEmpty()) {
            throw new IllegalArgumentException("Period cannot be empty");
        }
        if (periodStart == null) {
            throw new IllegalArgumentException("Period start cannot be null");
        }
        if (periodEnd == null) {
            throw new IllegalArgumentException("Period end cannot be null");
        }
        if (periodEnd.isBefore(periodStart)) {
            throw new IllegalArgumentException("Period end must be after period start");
        }
        if (generatedBy == null || generatedBy.trim().isEmpty()) {
            throw new IllegalArgumentException("Generated by cannot be empty");
        }
    }

    public static Builder builder() {
        return new Builder();
    }

    public static class Builder {
        private ReportId reportId;
        private String period;
        private Instant periodStart;
        private Instant periodEnd;
        private String generatedBy;

        public Builder reportId(ReportId reportId) {
            this.reportId = reportId;
            return this;
        }

        public Builder period(String period) {
            this.period = period;
            return this;
        }

        public Builder periodStart(Instant periodStart) {
            this.periodStart = periodStart;
            return this;
        }

        public Builder periodEnd(Instant periodEnd) {
            this.periodEnd = periodEnd;
            return this;
        }

        public Builder generatedBy(String generatedBy) {
            this.generatedBy = generatedBy;
            return this;
        }

        public GenerateConversionReportCommand build() {
            if (reportId == null) {
                reportId = ReportId.generate();
            }
            return new GenerateConversionReportCommand(
                reportId, period, periodStart, periodEnd, generatedBy
            );
        }
    }
}