quarkus.application.name=ky-billing-service
quarkus.http.port=8083
quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=postgresql://localhost:5432/syirkah_billing
quarkus.hibernate-orm.database.generation=none
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
