package tech.kayys.syirkah.project.application.command;

import tech.kayys.syirkah.foundation.application.command.Command;
import tech.kayys.syirkah.project.domain.project.ProjectType;

import java.util.Objects;
import java.util.UUID;

/**
 * Registers a new project.
 *
 * Note what is deliberately absent: no tenantId and no project id. The
 * tenant comes from the authenticated runtime context (never from a
 * client payload) and the identity is generated by the handler.
 */
public record CreateProjectCommand(
        String projectNumber,
        String name,
        ProjectType type,
        UUID customerId
) implements Command {

    public CreateProjectCommand {
        Objects.requireNonNull(projectNumber, "projectNumber cannot be null");
        Objects.requireNonNull(name, "name cannot be null");
        Objects.requireNonNull(type, "type cannot be null");
    }
}
