-- Vehicles
CREATE TABLE IF NOT EXISTS vehicles (
    id UUID PRIMARY KEY,
    registration_number VARCHAR(50) NOT NULL UNIQUE,
    vin VARCHAR(50) NOT NULL UNIQUE,
    make VARCHAR(100) NOT NULL,
    model VARCHAR(100) NOT NULL,
    year INTEGER NOT NULL,
    color VARCHAR(50),
    body_type VARCHAR(50),
    fuel_type VARCHAR(50),
    transmission VARCHAR(50),
    engine_size VARCHAR(50),
    horsepower VARCHAR(50),
    license_plate VARCHAR(20) NOT NULL,
    license_plate_state VARCHAR(50),
    license_plate_expiry_date VARCHAR(50),
    owner_id VARCHAR(255),
    owner_type VARCHAR(50),
    purchase_date DATE,
    purchase_price DECIMAL(19,2),
    currency_code VARCHAR(3),
    registration_date DATE,
    insurance_policy_number VARCHAR(100),
    insurance_provider VARCHAR(255),
    insurance_start_date DATE,
    insurance_end_date DATE,
    insurance_type VARCHAR(50),
    weight DECIMAL(19,4),
    gross_weight DECIMAL(19,4),
    length DECIMAL(19,4),
    width DECIMAL(19,4),
    height DECIMAL(19,4),
    seating_capacity INTEGER,
    fuel_tank_capacity DECIMAL(19,4),
    cargo_volume DECIMAL(19,4),
    max_payload DECIMAL(19,4),
    towing_capacity DECIMAL(19,4),
    fuel_efficiency DECIMAL(19,4),
    status VARCHAR(20) DEFAULT 'AVAILABLE',
    current_driver_id VARCHAR(255),
    current_location VARCHAR(255),
    current_latitude DECIMAL(10,8),
    current_longitude DECIMAL(11,8),
    total_distance_traveled DECIMAL(19,4),
    total_fuel_consumed DECIMAL(19,4),
    total_trips INTEGER,
    average_fuel_efficiency DECIMAL(19,4),
    current_mileage DECIMAL(19,4),
    last_maintenance_mileage DECIMAL(19,4),
    next_maintenance_mileage DECIMAL(19,4),
    assigned_to VARCHAR(255),
    assigned_to_name VARCHAR(255),
    gps_device_id VARCHAR(255),
    telematics_provider VARCHAR(255),
    real_time_tracking BOOLEAN DEFAULT TRUE,
    last_odometer_reading DECIMAL(19,4),
    last_location_update TIMESTAMP,
    notes TEXT,
    active BOOLEAN DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Drivers
CREATE TABLE IF NOT EXISTS drivers (
    id UUID PRIMARY KEY,
    employee_number VARCHAR(50) NOT NULL UNIQUE,
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    gender VARCHAR(20),
    date_of_birth DATE,
    nationality VARCHAR(50),
    personal_email VARCHAR(255),
    work_email VARCHAR(255),
    personal_phone VARCHAR(50),
    work_phone VARCHAR(50),
    address TEXT,
    city VARCHAR(100),
    state VARCHAR(100),
    postal_code VARCHAR(20),
    country VARCHAR(100),
    license_number VARCHAR(50) NOT NULL,
    license_class VARCHAR(20) NOT NULL,
    license_type VARCHAR(50),
    license_issue_date DATE,
    license_expiry_date DATE,
    license_state VARCHAR(50),
    endorsements_json TEXT,
    restrictions_json TEXT,
    company_id VARCHAR(255),
    department_id VARCHAR(255),
    hire_date DATE,
    employment_type VARCHAR(50),
    status VARCHAR(20) DEFAULT 'AVAILABLE',
    manager_id VARCHAR(255),
    manager_name VARCHAR(255),
    base_salary DECIMAL(19,2),
    overtime_rate DECIMAL(10,2),
    bonus_eligibility DECIMAL(10,2),
    incidents_json TEXT,
    trainings_json TEXT,
    safety_score DECIMAL(10,2),
    performance_score DECIMAL(10,2),
    total_trips INTEGER,
    total_distance DECIMAL(19,4),
    total_hours DECIMAL(19,4),
    citations INTEGER,
    accidents INTEGER,
    on_time_delivery_rate DECIMAL(10,2),
    shift_pattern VARCHAR(50),
    preferred_route VARCHAR(255),
    max_daily_hours DECIMAL(10,2),
    max_weekly_hours DECIMAL(10,2),
    max_monthly_hours DECIMAL(10,2),
    available BOOLEAN DEFAULT TRUE,
    current_vehicle_id VARCHAR(255),
    current_location VARCHAR(255),
    last_login TIMESTAMP,
    notes TEXT,
    active BOOLEAN DEFAULT TRUE,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    created_by VARCHAR(255),
    updated_by VARCHAR(255)
);

-- Fleet Analytics Cache
CREATE TABLE IF NOT EXISTS fleet_analytics_cache (
    id UUID PRIMARY KEY,
    analytics_json TEXT NOT NULL,
    calculated_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    version INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

-- Indexes
CREATE INDEX idx_vehicles_registration ON vehicles(registration_number);
CREATE INDEX idx_vehicles_status ON vehicles(status);
CREATE INDEX idx_vehicles_make ON vehicles(make);
CREATE INDEX idx_vehicles_model ON vehicles(model);

CREATE INDEX idx_drivers_employee ON drivers(employee_number);
CREATE INDEX idx_drivers_status ON drivers(status);
CREATE INDEX idx_drivers_license ON drivers(license_number);

CREATE INDEX idx_fleet_analytics_calculated ON fleet_analytics_cache(calculated_at);