quarkus.application.name=syirkah-pos-service
quarkus.http.port=8085
quarkus.datasource.db-kind=postgresql
quarkus.datasource.reactive.url=postgresql://localhost:5432/syirkah_pos
quarkus.hibernate-orm.database.generation=none
quarkus.smallrye-openapi.path=/openapi
quarkus.swagger-ui.always-include=true
